version: '3'
services:
    cms_mysql:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: cms
    cms_redis:
        image: redis:latest
        command: redis-server --requirepass 123456
        ports:
            - 6379:6379
        restart: always
    cms_minio:
        image: minio/minio:latest
        command: server /data --console-address 0.0.0.0:9090
        ports:
            - 9000:9000
        environment:
            MINIO_ROOT_USER: minio
            MINIO_ROOT_PASSWORD: wJalrXUtnFEMI/K7MDENG
        restart: always
    cms_minio_console:
        restart: always
        image: minio/console:latest
        ports:
            - 9090:9090
        environment:
            CONSOLE_MINIO_SERVER: http://0.0.0.0:9000
            CONSOLE_PBKDF_PASSPHRASE: minioadmin
            CONSOLE_PBKDF_SALT: minioadmin
        command: server
    cms_verdaccio:
        image: barolab/verdaccio
        ports:
            - 4873:4873
        volumes:
            - "./config:/verdaccio/conf"
        environment:
            VERDACCIO_PROTOCOL: http
            VERDACCIO_PORT: 4873

    cms_nginx:
        image: nginx:latest
        volumes:
            - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
            - "./nginx/js:/opt/js"
        ports:
            - "80:80"

